<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="3" failed="2" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-30T13:51:43 FJT" name="Functional Suite" finished-at="2021-10-30T13:51:43 FJT" duration-ms="406">
    <groups>
    </groups>
    <test started-at="2021-10-30T13:51:43 FJT" name="Login Test" finished-at="2021-10-30T13:51:43 FJT" duration-ms="69">
      <class name="testcases.TestCase1">
        <test-method is-config="true" signature="createDBConnection()[pri:0, instance:testcases.TestCase1@b62d79]" started-at="2021-10-30T13:51:43 FJT" name="createDBConnection" finished-at="2021-10-30T13:51:43 FJT" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createDBConnection -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:testcases.TestCase1@b62d79]" started-at="2021-10-30T13:51:43 FJT" name="launchBrowser" finished-at="2021-10-30T13:51:43 FJT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="doUserReg()[pri:1, instance:testcases.TestCase1@b62d79]" started-at="2021-10-30T13:51:43 FJT" name="doUserReg" finished-at="2021-10-30T13:51:43 FJT" duration-ms="9" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:testcases.TestCase1@b62d79]" started-at="2021-10-30T13:51:43 FJT" name="closeBrowser" finished-at="2021-10-30T13:51:43 FJT" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:testcases.TestCase1@b62d79]" started-at="2021-10-30T13:51:43 FJT" name="launchBrowser" finished-at="2021-10-30T13:51:43 FJT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method signature="doLogin()[pri:2, instance:testcases.TestCase1@b62d79]" started-at="2021-10-30T13:51:43 FJT" name="doLogin" finished-at="2021-10-30T13:51:43 FJT" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:testcases.TestCase1@b62d79]" started-at="2021-10-30T13:51:43 FJT" name="closeBrowser" finished-at="2021-10-30T13:51:43 FJT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="destroyDBConnection()[pri:0, instance:testcases.TestCase1@b62d79]" started-at="2021-10-30T13:51:43 FJT" name="destroyDBConnection" finished-at="2021-10-30T13:51:43 FJT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- destroyDBConnection -->
      </class> <!-- testcases.TestCase1 -->
    </test> <!-- Login Test -->
    <test started-at="2021-10-30T13:51:43 FJT" name="Validate Title Test" finished-at="2021-10-30T13:51:43 FJT" duration-ms="18">
      <class name="testcases.TestCase2">
        <test-method signature="validateTitles()[pri:0, instance:testcases.TestCase2@fba92d3]" started-at="2021-10-30T13:51:43 FJT" name="validateTitles" finished-at="2021-10-30T13:51:43 FJT" duration-ms="14" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Gmail.com> but was:<Yahoo.com>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Gmail.com> but was:<Yahoo.com>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at testcases.TestCase2.validateTitles(TestCase2.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTitles -->
      </class> <!-- testcases.TestCase2 -->
    </test> <!-- Validate Title Test -->
    <test started-at="2021-10-30T13:51:43 FJT" name="Dependency Test" finished-at="2021-10-30T13:51:43 FJT" duration-ms="99">
      <class name="testcases.TestCase3">
        <test-method signature="doUserReg()[pri:1, instance:testcases.TestCase3@bd4dc25]" started-at="2021-10-30T13:51:43 FJT" name="doUserReg" finished-at="2021-10-30T13:51:43 FJT" duration-ms="7" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User not registered successfully]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User not registered successfully
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at testcases.TestCase3.doUserReg(TestCase3.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doUserReg -->
        <test-method signature="doLogin()[pri:2, instance:testcases.TestCase3@bd4dc25]" started-at="2021-10-30T13:51:43 FJT" name="doLogin" finished-at="2021-10-30T13:51:43 FJT" depends-on-methods="testcases.TestCase3.doUserReg" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@bd4dc25] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.doLogin()[pri:2, instance:testcases.TestCase3@bd4dc25] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method signature="thirdTest()[pri:3, instance:testcases.TestCase3@bd4dc25]" started-at="2021-10-30T13:51:43 FJT" name="thirdTest" finished-at="2021-10-30T13:51:43 FJT" depends-on-methods="testcases.TestCase3.doUserReg" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- thirdTest -->
        <test-method signature="fourthTest()[pri:4, instance:testcases.TestCase3@bd4dc25]" started-at="2021-10-30T13:51:43 FJT" name="fourthTest" finished-at="2021-10-30T13:51:43 FJT" depends-on-methods="testcases.TestCase3.doUserReg" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestCase3.fourthTest()[pri:4, instance:testcases.TestCase3@bd4dc25] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestCase3.fourthTest()[pri:4, instance:testcases.TestCase3@bd4dc25] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fourthTest -->
      </class> <!-- testcases.TestCase3 -->
    </test> <!-- Dependency Test -->
  </suite> <!-- Functional Suite -->
</testng-results>
